version: '3'

services:
    mysql:
      image: mysql:5.7.29
      container_name: mysql
      ports: 
        - 3306:3306
      volumes:
#        - /home/fernandoreb/docker/volumes/mysql:/var/lib/mysql
        - ./mysql/volume:/var/lib/mysql
        - ./mysql/scripts:/docker-entrypoint-initdb.d
        - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      environment:
        MYSQL_ROOT_PASSWORD : 'root'
        MYSQL_USER: lojaonline
        MYSQL_PASSWORD: lojaonline
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: dev_pma
      links:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306  
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8183:80
    keycloak:
      image: jboss/keycloak:9.0.2
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "8080"]
        interval: 10s
        retries: 5
      ports:
        - "8180:8080"
        - "8443:8443"
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: KEYCLOAK
        DB_USER: lojaonline
        DB_PASSWORD: lojaonline
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        JDBC_PARAMS: "useSSL=false"
      depends_on:
        - mysql
    mongo:
      image: mongo:3.4.23-xenial
      ports: 
        - 27017:27017
        - 28017:28017
      volumes: 
        - /home/fernandoreb/docker/volumes/mongodb:/data/db
      restart: always
      environment:
        AUTH: 'no'

    redis:
      image: redis:5.0.6-alpine
      ports: 
        - 6379:6379
      restart: always

    jbpm:
      image: fernandoreb/jbpm-server-7.51.0.final-dist:1.0.3
      ports: 
        - 8082:8080
      volumes:
        - ./jbpm-server/standalone/configuration/standalone.xml:/jbpm/jbpm-server-7.51.0.Final-dist/standalone/configuration/standalone.xml
        - ./jbpm-server/standalone/configuration/standalone.conf:/jbpm/jbpm-server-7.51.0.Final-dist/standalone/configuration/standalone.conf
        - ./jbpm-server/volumes/standalone_data:/jbpm/jbpm-server-7.51.0.Final-dist/standalone/data
        - ./jbpm-server/volumes/niogit:/jbpm/jbpm-server-7.51.0.Final-dist/.niogit
        - ./jbpm-server/volumes/niogit-caseapp:/jbpm/jbpm-server-7.51.0.Final-dist/.niogit-caseapp
        - ./jbpm-server/volumes/repositories:/jbpm/jbpm-server-7.51.0.Final-dist/repositories
        - ./jbpm-server/volumes/index:/jbpm/jbpm-server-7.51.0.Final-dist/.index
        - ./jbpm-server/volumes/m2:$HOME/.m2
      restart: always

#    service-loja-online:
#      depends_on:
#        - mongo
#        - redis
#        - jbpm
#        - keycloack
#      image: fernandoreb/service-loja-online
#      ports: 
#        - 3000:3000
#      links:
#        - mongo
#        - redis
#      restart: always
