---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - name: admin-node
              containerPort: 8082
            - name: broker
              containerPort: 29092
              hostPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:32181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://192.168.0.27:29092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafkaadm-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
  - name: admin-node
    protocol: TCP
    port: 8082
    targetPort: 8082
