---
apiVersion: v1
kind: Service
metadata:
  name: sales-taxes-service-service
spec:
  type: NodePort
  selector:
    app: sales-taxes-service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
