---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-taxes-service-deployment
  labels:
    app: sales-taxes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-taxes-service
  template:
    metadata:
      labels:
        app: sales-taxes-service
    spec:
      containers:
        - name: sales-taxes-service
          image: fernandoreb/sales-taxes-service:1.0.1
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: sales-taxes-service-secret
                  key: ROOT_PASSWORD
