---
apiVersion: v1
kind: Service
metadata:
  name: service-loja-online-service
spec:
  type: NodePort
  selector:
    app: service-loja-online
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
